# Generated by Django 3.0.3 on 2020-03-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50)),
                ('outliers_amount', models.IntegerField()),
                ('lines_amount', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('period', models.CharField(max_length=20)),
                ('sensor_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Device')),
                ('sensor_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Distribution')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SensorType')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sensor')),
            ],
        ),
    ]
