# Generated by Django 3.0.3 on 2020-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_distribution_distributionparameters_sensor_sensortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='code',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='outliers_amount',
            field=models.IntegerField(default=0),
        ),
    ]
