# Generated by Django 3.0.3 on 2020-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200329_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='period',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
