# Generated by Django 3.0.3 on 2020-04-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
            preserve_default=False,
        ),
    ]
