# Generated by Django 3.0.3 on 2020-04-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_report_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportSensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Report')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SensorType')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Report')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sensor')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SensorType')),
            ],
        ),
    ]
